# ReportSync
# By Rodrigo R.

discord:
  enabled: true
  bot_token: "..." # Get it from https://discord.com/developers/applications
  # Should we sync reports with Discord?
  channel_id: "0" # The channel ID where the reports will be sent
  embed:
    title: "New report recieved"
    description: "%executor% reported %target% for %reason% on %server%"
    # %server% will be replaced with the world name if the plugin is running Spigot
    color: 0xFF0000
    # Those placeholders are available on all options
    url: null
    image: null
    thumbnail: null
    author:
      name: null
      icon_url: null
    footer:
      text: null
      icon_url: null

messages:
  error_console: "&cYou cannot use this command in console."
  error_report_staff: "&cYou cannot report staff members!"
  error_staff_report: "&cYou cannot report users if you are a staff member!"
  error_report_self: "&cYou cannot report yourself!"
  error_no_permission: "&cYou don't have permission to use this command."
  error_not_online: "&cThat user is not online."
  report_sent: "&aYour report has been sent!"
  config_reloaded: "&aConfig has been reloaded!"
  usage: "&cUsage: /report <user> <reason>"
  report_recieved:
    - "&6This message was generated by ReportSync"
    - "&aReport received"
    - "&aExecutor: %executor%"
    - "&aReported user: %target%"
    - "&aReason: %reason%"
    - "&aServer: %server%" # %server% will be replaced with the world name if the plugin is running Spigot

overrides:
  report_staff: false # Allow users to report staff members
  staff_report: false # Allow staff members to report users
  hide_reload: true
  # When a user tries to reload the config without having the permission, the plugin will not show the "error_no_permission" message
  # Instead, it will take it as a normal report and continue with the normal report function

# Secret uses: /report reload
# Use the reload command to reload the config
# If a player named "reload" is on the server, the plugin will detect it and do the report function instead reloading

# Permissions:
# reportsync.reload - Reload the config
# reportsync.report - Use the /report command
# reportsync.staff - Bypass and receive reports (Staff members only)